routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Configurations
Route::redirect('/', '/home');
Auth::routes(['verify' => true]);

// Free Views
Route::view('/about', 'app.about')->name('about');
Route::view('/contact-us', 'app.contact-us')->name('contact-us');
Route::view('/faqs', 'app.faqs')->name('faqs');
Route::view('/posting-policy', 'app.posting-policy')->name('posting-policy');
Route::view('/privacy-policy', 'app.privacy-policy')->name('privacy-policy');
Route::view('/terms-of-use', 'app.terms-of-use')->name('terms-of-use');

// Free Routes
Route::get('/home', 'HomeController')->name('home');
Route::get('/retails', 'RetailController')->name('retails');
Route::get('/wholesales', 'WholesaleController')->name('wholesales');
Route::get('/auctions', 'AuctionController')->name('auctions');
Route::get('/reverse-auctions', 'ReverseAuctionController')->name('reverse-auctions');
Route::get('/search', 'SearchController@search')->name('search');
Route::get('/suggestion', 'SearchController@suggestion')->name('suggestion');
Route::get('/jobs/search', 'SearchController@searchJob')->name('search.job');
Route::get('/real-estates/search', 'SearchController@searchRealEstate')->name('search.real-estate');
Route::get('/travels/search', 'SearchController@searchTravel')->name('search.travel');
Route::get('/vehicles/search', 'SearchController@searchVehicle')->name('search.vehicle');

// Throttle
Route::group(['middleware' => ['throttle:60,1']], function () {
    // User Auth
    Route::namespace('Auth')->group(function () {
        Route::get('/logout', 'LoginController@logout')->name('logout');

        Route::get('/login/facebook', 'LoginController@facebookLogin')->name('facebook.login');
        Route::get('/login/facebook/callback', 'LoginController@facebookCallback')->name('facebook.callback');

        Route::get('/login/google', 'LoginController@googleLogin')->name('google.login');
        Route::get('/login/google/callback', 'LoginController@googleCallback')->name('google.callback');

        Route::get('/login/linkedin', 'LoginController@linkedinLogin')->name('linkedin.login');
        Route::get('/login/linkedin/callback', 'LoginController@linkedinCallback')->name('linkedin.callback');

        Route::get('/login/instagram', 'LoginController@instagramLogin')->name('instagram.login');
        Route::get('/login/instagram/callback', 'LoginController@instagramCallback')->name('instagram.callback');
    });

    // Community Resources
    Route::resource('communities.categories', 'CommunityCategoryController')->except(['create', 'edit'])->shallow();
    Route::resource('communities.comments', 'CommunityCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('communities.images', 'CommunityImageController')->except(['create', 'edit'])->shallow();

    // Job Resources
    Route::resource('jobs.addresses', 'JobAddressController')->except(['create', 'edit'])->shallow();
    Route::resource('jobs.categories', 'JobCategoryController')->except(['create', 'edit'])->shallow();
    Route::resource('jobs.comments', 'JobCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('jobs.images', 'JobImageController')->except(['create', 'edit'])->shallow();

    // Product Resources
    Route::resource('products.addresses', 'ProductAddressController')->except(['create', 'edit'])->shallow();
    Route::resource('products.bids', 'ProductBidController')->except(['create', 'edit'])->shallow();
    Route::resource('products.categories', 'ProductCategoryController')->except(['create', 'edit'])->shallow();
    Route::resource('products.comments', 'ProductCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('products.images', 'ProductImageController')->except(['create', 'edit'])->shallow();
    Route::resource('products.watchables', 'ProductWatchableController')->except(['create', 'edit'])->shallow();

    // Real Estate Resources
    Route::resource('real-estates.addresses', 'RealEstateAddressController')->except(['create', 'edit'])->shallow();
    Route::resource('real-estates.bids', 'RealEstateBidController')->except(['create', 'edit'])->shallow();
    Route::resource('real-estates.categories', 'RealEstateCategoryController')->except(['create', 'edit'])->shallow();
    Route::resource('real-estates.comments', 'RealEstateCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('real-estates.images', 'RealEstateImageController')->except(['create', 'edit'])->shallow();
    Route::resource('real-estates.watchables', 'RealEstateWatchableController')->except(['create', 'edit'])->shallow();

    // Service Resources
    Route::resource('services.addresses', 'ServiceAddressController')->except(['create', 'edit'])->shallow();
    Route::resource('services.bids', 'ServiceBidController')->except(['create', 'edit'])->shallow();
    Route::resource('services.categories', 'ServiceCategoryController')->except(['create', 'edit'])->shallow();
    Route::resource('services.comments', 'ServiceCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('services.feedbacks', 'ServiceFeedbackController')->except(['create', 'edit'])->shallow();
    Route::resource('services.images', 'ServiceImageController')->except(['create', 'edit'])->shallow();
    Route::resource('services.watchables', 'ServiceWatchableController')->except(['create', 'edit'])->shallow();

    // Travel Resources
    Route::resource('travels.addresses', 'TravelAddressController')->except(['create', 'edit'])->shallow();
    Route::resource('travels.bids', 'TravelBidController')->except(['create', 'edit'])->shallow();
    Route::resource('travels.categories', 'TravelCategoryController')->except(['create', 'edit'])->shallow();
    Route::resource('travels.comments', 'TravelCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('travels.images', 'TravelImageController')->except(['create', 'edit'])->shallow();
    Route::resource('travels.watchables', 'TravelWatchableController')->except(['create', 'edit'])->shallow();

    // User Resources
    Route::resource('users.addresses', 'UserAddressController')->except(['create', 'edit'])->shallow();
    Route::resource('users.ads', 'UserAdController')->except(['edit'])->shallow();
    Route::resource('users.bids', 'UserBidController')->except(['create', 'edit'])->shallow();
    Route::resource('users.comments', 'UserCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('users.communities', 'UserCommunityController')->except(['edit'])->shallow();
    Route::resource('users.feedbacks', 'UserFeedbackController')->except(['create', 'edit'])->shallow();
    Route::resource('users.images', 'UserImageController')->except(['create', 'edit'])->shallow();
    Route::resource('users.jobs', 'UserJobController')->except(['edit'])->shallow();
    Route::resource('users.products', 'UserProductController')->except(['edit'])->shallow();
    Route::resource('users.real-estates', 'UserRealEstateController')->except(['edit'])->shallow();
    Route::resource('users.services', 'UserServiceController')->except(['edit'])->shallow();
    Route::resource('users.travels', 'UserTravelController')->except(['edit'])->shallow();
    Route::resource('users.vehicles', 'UserVehicleController')->except(['edit'])->shallow();
    Route::resource('users.watchables', 'UserWatchableController')->except(['create', 'edit'])->shallow();

    // Vehicle Resources
    Route::resource('vehicles.addresses', 'VehicleAddressController')->except(['create', 'edit'])->shallow();
    Route::resource('vehicles.bids', 'VehicleBidController')->except(['create', 'edit'])->shallow();
    Route::resource('vehicles.categories', 'VehicleCategoryController')->except(['create', 'edit'])->shallow();
    Route::resource('vehicles.comments', 'VehicleCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('vehicles.images', 'VehicleImageController')->except(['create', 'edit'])->shallow();
    Route::resource('vehicles.watchables', 'VehicleWatchableController')->except(['create', 'edit'])->shallow();

    // Wholesale Actions
    Route::get('wholesales/requests', 'WholesaleRequestController@index')->name('wholesales.requests.index');
    Route::post('wholesales/requests', 'WholesaleRequestController@request')->name('wholesales.requests.store');
    Route::put('wholesales/requests/{wholesaleRequest}/approve', 'WholesaleRequestController@approve')->name('wholesales.requests.approve');
    Route::put('wholesales/requests/{wholesaleRequest}/deny', 'WholesaleRequestController@deny')->name('wholesales.requests.deny');

    // Accounts
    Route::get('/account', 'AccountController')->name('account');
    Route::get('/listings', 'ListingController')->name('listings');
    Route::get('/analytics', 'AnalyticsController')->name('analytics');

    
    // Stripe
    Route::post('/stripe/checkout', 'StripeController@checkout')->name('stripe.checkout');
    Route::get('/stripe/success', 'StripeController@success')->name('stripe.success');
    Route::get('/stripe/cancel', 'StripeController@cancel')->name('stripe.cancel');
    Route::get('/stripe/connect/success', 'StripeController@connectSuccess')->name('stripe.connect.success');

    // Cart
    Route::get('/cart', 'CartController@show')->name('cart.show');
    Route::post('/cart', 'CartController@add')->name('cart.add');
    Route::put('/cart/{id}', 'CartController@update')->name('cart.update');
    Route::delete('/cart/{id}', 'CartController@remove')->name('cart.remove');
    Route::delete('/cart/clear', 'CartController@clear')->name('cart.clear');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Nicolaslopezj\Searchable\SearchableTrait;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable, SoftDeletes, SearchableTrait;

    protected $guarded = [
        'type',
        'status',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $dates = ['birth_date'];

    protected $searchable = [
        'columns' => [
            'users.first_name' => 10,
            'users.last_name' => 10,
        ],
    ];

    public function address()
    {
        return $this->morphOne('App\Address', 'addressable');
    }

    public function ads()
    {
        return $this->hasMany('App\Ad');
    }

    public function bids()
    {
        return $this->hasMany('App\Bid');
    }

    public function comments()
    {
        return $this->hasMany('App\Comment');
    }

    public function communities()
    {
        return $this->hasMany('App\Community');
    }

    public function feedbacks()
    {
        return $this->hasMany('App\Feedback');
    }

    public function image()
    {
        return $this->morphOne('App\Image', 'imageable')->latest();
    }

    public function jobs()
    {
        return $this->hasMany('App\Job');
    }

    public function jobWatchlist()
    {
        return $this->morphedByMany('App\Job', 'watchable')
                    ->withPivot('id');
    }

    public function memberships()
    {
        return $this->belongsToMany('App\Membership')
            ->as('membership')
            ->withPivot(
                'sales_count',
                'sales_cost'
            )
            ->withTimestamps();
    }

    public function products()
    {
        return $this->hasMany('App\Product');
    }

    public function productWatchlist()
    {
        return $this->morphedByMany('App\Product', 'watchable')
                    ->withPivot('id');
    }

    public function realEstates()
    {
        return $this->hasMany('App\RealEstate');
    }

    public function realEstateWatchlist()
    {
        return $this->morphedByMany('App\RealEstate', 'watchable')
                    ->withPivot('id');
    }

    public function services()
    {
        return $this->hasMany('App\Service');
    }

    public function serviceWatchlist()
    {
        return $this->morphedByMany('App\Service', 'watchable')
                    ->withPivot('id');
    }

    public function travels()
    {
        return $this->hasMany('App\Travel');
    }

    public function travelWatchlist()
    {
        return $this->morphedByMany('App\Travel', 'watchable')
                    ->withPivot('id');
    }

    public function vehicles()
    {
        return $this->hasMany('App\Vehicle');
    }

    public function vehicleWatchlist()
    {
        return $this->morphedByMany('App\Vehicle', 'watchable')
                    ->withPivot('id');
    }

    public function requests()
    {
        return $this->hasMany('App\WholesaleRequest', 'vendor_id');
    }

    public function wholesaleRequests()
    {
        return $this->hasMany('App\WholesaleRequest', 'buyer_id');
    }

    public function getFullNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }

    public function getProfilePlaceholderAttribute()
    {
        return $this->gender === 'Male' ? asset('img/matt.jpg') : asset('img/kristy.jpg');
    }

    public function getIsActiveAttribute()
    {
        return $this->status === 'active' ? true : false;
    }

    public function getIsBusinessManAttribute()
    {
        return $this->type === 'Business' ? true : false;
    }

    public function scopeActive($query)
    {
        return $query->whereStatus('active');
    }
}

resources/views/partials/admin-footer.blade.php
<footer class="footer">
    <div class="row align-items-center justify-content-xl-between">
        <div class="col-xl-6">
            <div class="copyright text-center text-xl-left text-muted">
                &copy; 2020 GC Trader
            </div>
        </div>
        <div class="col-xl-6">
            <ul
                class="nav nav-footer justify-content-center justify-content-xl-end"
            >
                <li class="nav-item">
                    <a href="{{ route('terms-of-use') }}" class="nav-link"
                        >Terms of Use</a
                    >
                </li>
                <li class="nav-item">
                    <a href="{{ route('privacy-policy') }}" class="nav-link"
                        >Privacy Policy</a
                    >
                </li>
                <li class="nav-item">
                    <a href="{{ route('posting-policy') }}" class="nav-link"
                        >Posting Policy</a
                    >
                </li>
            </ul>
        </div>
    </div>
</footer>

resources/views/partials/admin-forms.blade.php
<form id="communityToggleForm" method="POST">
    @csrf @method('PUT')
    <input type="hidden" name="status" />
</form>

resources/views/partials/app-account-nav.blade.php
<div class="my-5 mx-3 md:mx-5 lg:mx-20 flex flex-col md:flex-row justify-between hidden md:block">
    <div class="ui secondary menu">
        <a
            href="{{ route('account') }}"
            class="@if(Route::currentRouteName() === 'account') active @endif item"
        >
            My account
        </a>
        <a
            href="{{ route('listings') }}"
            class="@if(Route::currentRouteName() === 'listings') active @endif item"
        >
            My Listings
        </a>
        <a
            href="{{ route('analytics') }}"
            class="@if(Route::currentRouteName() === 'analytics') active @endif item"
        >
            Analytics
        </a>
        <a
            href="{{ route('wholesales.requests.index') }}"
            class="@if(Route::currentRouteName() === 'wholesales.requests.index') active @endif item"
        >
            Wholesale Requests
        </a>
        {{-- <a
            href="{{ route('users.ads.index', Auth::id()) }}"
            class="@if(Route::currentRouteName() === 'users.ads.index') active @endif item"
        >
            Ads
        </a> --}}
    </div>
    @if (Auth::user()->is_active)
        <div>
            <div class="ui floating labeled icon dropdown button primary">
                <i class="plus icon"></i>
                <span class="text">Add Listing</span>
                <div class="menu">
                    <a
                        href="{{ route('users.products.create', Auth::id()) }}"
                        class="item"
                    >
                        New Product
                    </a>
                    <a
                        href="{{ route('users.vehicles.create', Auth::id()) }}"
                        class="item"
                    >
                        New Vehicle
                    </a>
                    <a
                        href="{{ route('users.travels.create', Auth::id()) }}"
                        class="item"
                    >
                        New Travel
                    </a>
                    @can('create-service', Service::class)
                        <a
                            href="{{ route('users.services.create', Auth::id()) }}"
                            class="item"
                        >
                            New Service
                        </a>
                    @endcan
                    <a
                        href="{{ route('users.real-estates.create', Auth::id()) }}"
                        class="item"
                    >
                        New Real Estate
                    </a>
                    <a
                        href="{{ route('users.communities.create', Auth::id()) }}"
                        class="item"
                    >
                        New Community
                    </a>
                    <a
                        href="{{ route('users.jobs.create', Auth::id()) }}"
                        class="item"
                    >
                        New Job
                    </a>
                </div>
            </div>
        </div>
    @endif
</div>
<nav class="flex m-3 items-center justify-start md:hidden">
    @if (Auth::user()->is_active)
        <div class="ui floating icon dropdown button primary p-2">
            <i class="plus icon"></i>
            <div class="menu">
                <a
                    href="{{ route('users.products.create', Auth::id()) }}"
                    class="item"
                >
                    New Product
                </a>
                <a
                    href="{{ route('users.vehicles.create', Auth::id()) }}"
                    class="item"
                >
                    New Vehicle
                </a>
                <a
                    href="{{ route('users.travels.create', Auth::id()) }}"
                    class="item"
                >
                    New Travel
                </a>
                @can('create-service', Service::class)
                    <a
                        href="{{ route('users.services.create', Auth::id()) }}"
                        class="item"
                    >
                        New Service
                    </a>
                @endcan
                <a
                    href="{{ route('users.real-estates.create', Auth::id()) }}"
                    class="item"
                >
                    New Real Estate
                </a>
                <a
                    href="{{ route('users.communities.create', Auth::id()) }}"
                    class="item"
                >
                    New Community
                </a>
                <a
                    href="{{ route('users.jobs.create', Auth::id()) }}"
                    class="item"
                >
                    New Job
                </a>
            </div>
        </div>
    @endif
    <div class="ui floating labeled icon dropdown button">
        <i class="bars icon"></i>
        <span class="text">Account</span>
        <div class="menu">
            <a href="{{ route('account') }}" class="item">
                My Account
            </a>
            <a href="{{ route('listings') }}" class="item">
                My Listings
            </a>
            <a href="{{ route('users.watchables.index', auth()->id()) }}" class="item">
                Watchlist
            </a>
            <a href="{{ route('analytics') }}" class="item">
                Analytics
            </a>
            <a href="{{ route('wholesales.requests.index') }}" class="item">
                Wholesale Requests
            </a>
            <a href="{{ route('users.ads.index', Auth::id()) }}" class="item">
                Ads
            </a>
        </div>
    </div>
</nav>

resources/views/partials/app-dropzone-preview.blade.php
<div class="hidden" id="tpl">
    <div class="dz-preview dz-file-preview mt-5">
        <div class="ui blue indicating tiny progress" style="margin-bottom: 0 !important">
            <div class="bar" data-dz-uploadprogress></div>
        </div>
        <div class="ui very relaxed list text-center">
            <div class="item" data-dz-remove>
                <img class="ui avatar image" data-dz-thumbnail />
                <div class="content">
                    <span class="header w-56 overflow-hidden" data-dz-name></span>
                    <div class="description">
                        <span data-dz-size></span> loaded
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="hidden" id="tpl-video">
  <div class="dz-preview dz-file-preview mt-5">
      <div class="ui blue indicating tiny progress" style="margin-bottom: 0 !important">
          <div class="bar" data-dz-uploadprogress></div>
      </div>
      <div class="ui very relaxed list text-center">
          <div class="item" data-dz-remove>
              <video controls autoplay class="ui avatar image center">
                  <source type="video/mp4" data-dz-thumbnail>
              </video>
              <div class="content">
                  <span class="header w-56 overflow-hidden" data-dz-name></span>
                  <div class="description">
                      <span data-dz-size></span> loaded
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>

resources/views/partials/app-footer.blade.php
<footer class="md:flex flex-col text-white p-10 md:px-5 md:py-10 lg:p-20">
    <div class="container mx-auto">
        <div class="md:flex justify-between">
            <div class="md:mx-3">
                <h4 class="font-bold">
                    Subscribe to receive upcoming auctions
                    <br />
                    and special offers!
                </h4>
                <form
                    method="POST"
                    action="{{ route('email-subscription.store') }}"
                    class="ui form my-5"
                >
                    @csrf
                    <div class="field">
                        <label>Email Address</label>
                        <input
                            type="email"
                            name="email"
                            placeholder="Someone@email.com"
                            required
                        />
                    </div>
                    <button class="ui button primary" type="submit">
                        Subscribe
                    </button>
                </form>
            </div>
            <div class="mt-10 md:mt-0 md:mx-3">
                <h4 class="font-bold">Top Categories</h4>
                <div class="ui link list">
                    <a href="{{ route('communities.index') }}" class="item">Community</a>
                    <a href="{{ route('jobs.index') }}" class="item">Jobs</a>
                    <a href="{{ route('real-estates.index') }}" class="item">Real Estate</a>
                    <a href="{{ route('services.index') }}" class="item">Services</a>
                    <a href="{{ route('travels.index') }}" class="item">Travel</a>
                    <a href="{{ route('vehicles.index') }}" class="item">Vehicle</a>
                </div>
            </div>
            <div class="mt-10 md:mt-0 md:mx-3">
                <h4 class="font-bold">Tips & help</h4>
                <div class="ui link list">
                    <a href="{{ route('about') }}" class="item">About GC Trader</a>
                    <a href="{{ route('faqs') }}" class="item">FAQs</a>
                    <a href="{{ route('contact-us') }}" class="item">Contact Us</a>
                    @if (Auth::guest())
                        <a href="{{ route('login') }}" class="item">Login</a>
                        <a href="{{ route('register') }}" class="item">Register</a>
                    @else
                        <div></div>
                    @endif
                    
                </div>
            </div>
            <div class="mt-10 md:mt-0 md:mx-3">
                <h4 class="font-bold">Legal</h4>
                <div class="ui link list">
                    <a href="{{ route('terms-of-use') }}" class="item">Terms of Use</a>
                    <a href="{{ route('privacy-policy') }}" class="item">Privacy Policy</a>
                    <a href="{{ route('posting-policy') }}" class="item">Posting Policy</a>
                </div>
            </div>
            <div class="mt-10 md:mt-0 md:mx-3">
                <h4 class="font-bold">Payment Methods</h4>
                <div class="my-3">
                    <i class="cc stripe icon big"></i>
                    {{-- <i class="cc amex icon big"></i>
                    <i class="cc mastercard icon big"></i>
                    <i class="cc paypal icon big"></i>
                    <i class="cc visa icon big"></i> --}}
                </div>
            </div>
        </div>
        <h4 class="text-center my-20">© GC Trader 2020</h4>
    </div>
</footer>

resources/views/partials/app-upper-nav.blade.php
<div class="flex justify-center md:hidden">
    @if ($bannerAds->count())
        <img
            class="w-100 mx-auto"
            src="{{ asset($bannerAds->random()->image->src) }}"
        />
    @else
        <div class="ui centered banner test ad" data-text="PUT YOUR AD HERE"></div>
    @endif
</div>
<nav class="flex m-3 items-center justify-between md:hidden">
    <a href="{{ route('home') }}">
        <img src="{{ asset('img/logo.jpg') }}" width="100px" />
    </a>
    <div class="ui floating labeled icon dropdown button">
        <i class="bars icon"></i>
        <span class="text">Menu</span>
        <div class="menu">
            @auth
                @if (auth()->user()->is_business_man)
                    <a href="{{ route('auctions') }}" class="item">
                        Auction
                    </a>
                @endif
                @if (Gate::check('view-any-wholesale-product'))
                    <a href="{{ route('wholesales') }}" class="item">
                        Wholesale
                    </a>
                @endif
            @endauth

            <a href="{{ route('communities.index') }}" class="item">
                Community
            </a>
            <a href="{{ route('jobs.index') }}" class="item">
                Job
            </a>
            <a href="{{ route('real-estates.index') }}" class="item">
                Real Estate
            </a>
            <a href="{{ route('travels.index') }}" class="item">
                Travel
            </a>
            <a href="{{ route('vehicles.index') }}" class="item">
                Vehicle
            </a>
            <div class="divider"></div>
            @guest
                <a href="{{ route('login') }}" class="item">
                    Login
                </a>
                <a href="{{ route('register') }}" class="item">
                    Register
                </a>
            @endguest
            @auth
                <a href="{{ route('cart.show') }}" class="item">
                    Cart
                </a>
                <a href="{{ route('account') }}" class="item">
                    {{ auth()->user()->first_name }}
                </a>
                <a href="{{ route('logout') }}" class="item">
                    Logout
                </a>
            @endauth
        </div>
    </div>
</nav>
<nav class="hidden md:block container mx-auto">
    <div class="flex justify-between my-5 mx-3 lg:mx-20">
        <div class="w-1/6">
            <a href="{{ route('home') }}" class="my-auto">
                <img src="{{ asset('img/logo.jpg') }}" width="150px" />
            </a>
        </div>
        <div class="w-5/6">
            <div class="flex flex-col justify-between h-full">
                @if ($bannerAds->count())
                    <div class="mx-auto">
                        <img src="{{ asset($bannerAds->random()->image->src) }}" />
                    </div>
                @else
                    <div
                        class="ui centered banner test ad"
                        data-text="PUT YOUR AD HERE"
                    ></div>
                @endif
                <div class="flex justify-between">
                    <ul class="flex">
                        <li class="mx-5 text-blue-700 font-bold">
                            <a href="{{ route('communities.index') }}">Community</a>
                        </li>
                        <li class="mx-5 text-blue-700 font-bold">
                            <a href="{{ route('jobs.index') }}">Job</a>
                        </li>
                        <li class="mx-5 text-blue-700 font-bold">
                            <a href="{{ route('real-estates.index') }}">Real Estate</a>
                        </li>
                        <li class="mx-5 text-blue-700 font-bold">
                            <a href="{{ route('services.index') }}">Service</a>
                        </li>
                        <li class="mx-5 text-blue-700 font-bold">
                            <a href="{{ route('travels.index') }}">Travel</a>
                        </li>
                        <li class="mx-5 text-blue-700 font-bold">
                            <a href="{{ route('vehicles.index') }}">Vehicle</a>
                        </li>
                    </ul>
                    <ul class="flex">
                        @guest
                            <li class="mx-5 text-blue-700 font-bold">
                                <a href="{{ route('login') }}">Login</a>
                            </li>
                            <li class="mx-5 text-blue-700 font-bold hidden lg:block">
                                <a href="{{ route('register') }}">Register</a>
                            </li>
                        @endguest
                        @auth
                            <li class="mx-5 text-blue-700 font-bold hidden lg:block">
                                <a href="{{ route('account') }}"
                                    >{{ auth()->user()->first_name }}</a
                                >
                            </li>
                            <li class="mx-5 text-blue-700 font-bold">
                                <a href="{{ route('logout') }}">Logout</a>
                            </li>
                        @endauth
                    </ul>
                </div>
            </div>
        </div>
    </div>
</nav>