routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Configurations
Route::redirect('/', '/home');
Auth::routes(['verify' => true]);

// Free Views
Route::view('/about', 'app.about')->name('about');
Route::view('/contact-us', 'app.contact-us')->name('contact-us');
Route::view('/faqs', 'app.faqs')->name('faqs');
Route::view('/posting-policy', 'app.posting-policy')->name('posting-policy');
Route::view('/privacy-policy', 'app.privacy-policy')->name('privacy-policy');
Route::view('/terms-of-use', 'app.terms-of-use')->name('terms-of-use');

// Free Routes
Route::get('/home', 'HomeController')->name('home');
Route::get('/retails', 'RetailController')->name('retails');
Route::get('/wholesales', 'WholesaleController')->name('wholesales');
Route::get('/auctions', 'AuctionController')->name('auctions');
Route::get('/reverse-auctions', 'ReverseAuctionController')->name('reverse-auctions');
Route::get('/search', 'SearchController@search')->name('search');
Route::get('/suggestion', 'SearchController@suggestion')->name('suggestion');
Route::get('/jobs/search', 'SearchController@searchJob')->name('search.job');
Route::get('/real-estates/search', 'SearchController@searchRealEstate')->name('search.real-estate');
Route::get('/travels/search', 'SearchController@searchTravel')->name('search.travel');
Route::get('/vehicles/search', 'SearchController@searchVehicle')->name('search.vehicle');

// Throttle
Route::group(['middleware' => ['throttle:60,1']], function () {
    // User Auth
    Route::namespace('Auth')->group(function () {
        Route::get('/logout', 'LoginController@logout')->name('logout');

        Route::get('/login/facebook', 'LoginController@facebookLogin')->name('facebook.login');
        Route::get('/login/facebook/callback', 'LoginController@facebookCallback')->name('facebook.callback');

        Route::get('/login/google', 'LoginController@googleLogin')->name('google.login');
        Route::get('/login/google/callback', 'LoginController@googleCallback')->name('google.callback');

        Route::get('/login/linkedin', 'LoginController@linkedinLogin')->name('linkedin.login');
        Route::get('/login/linkedin/callback', 'LoginController@linkedinCallback')->name('linkedin.callback');

        Route::get('/login/instagram', 'LoginController@instagramLogin')->name('instagram.login');
        Route::get('/login/instagram/callback', 'LoginController@instagramCallback')->name('instagram.callback');
    });

    // Community Resources
    Route::resource('communities.categories', 'CommunityCategoryController')->except(['create', 'edit'])->shallow();
    Route::resource('communities.comments', 'CommunityCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('communities.images', 'CommunityImageController')->except(['create', 'edit'])->shallow();

    // Job Resources
    Route::resource('jobs.addresses', 'JobAddressController')->except(['create', 'edit'])->shallow();
    Route::resource('jobs.categories', 'JobCategoryController')->except(['create', 'edit'])->shallow();
    Route::resource('jobs.comments', 'JobCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('jobs.images', 'JobImageController')->except(['create', 'edit'])->shallow();

    // Product Resources
    Route::resource('products.addresses', 'ProductAddressController')->except(['create', 'edit'])->shallow();
    Route::resource('products.bids', 'ProductBidController')->except(['create', 'edit'])->shallow();
    Route::resource('products.categories', 'ProductCategoryController')->except(['create', 'edit'])->shallow();
    Route::resource('products.comments', 'ProductCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('products.images', 'ProductImageController')->except(['create', 'edit'])->shallow();
    Route::resource('products.watchables', 'ProductWatchableController')->except(['create', 'edit'])->shallow();

    // Real Estate Resources
    Route::resource('real-estates.addresses', 'RealEstateAddressController')->except(['create', 'edit'])->shallow();
    Route::resource('real-estates.bids', 'RealEstateBidController')->except(['create', 'edit'])->shallow();
    Route::resource('real-estates.categories', 'RealEstateCategoryController')->except(['create', 'edit'])->shallow();
    Route::resource('real-estates.comments', 'RealEstateCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('real-estates.images', 'RealEstateImageController')->except(['create', 'edit'])->shallow();
    Route::resource('real-estates.watchables', 'RealEstateWatchableController')->except(['create', 'edit'])->shallow();

    // Service Resources
    Route::resource('services.addresses', 'ServiceAddressController')->except(['create', 'edit'])->shallow();
    Route::resource('services.bids', 'ServiceBidController')->except(['create', 'edit'])->shallow();
    Route::resource('services.categories', 'ServiceCategoryController')->except(['create', 'edit'])->shallow();
    Route::resource('services.comments', 'ServiceCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('services.feedbacks', 'ServiceFeedbackController')->except(['create', 'edit'])->shallow();
    Route::resource('services.images', 'ServiceImageController')->except(['create', 'edit'])->shallow();
    Route::resource('services.watchables', 'ServiceWatchableController')->except(['create', 'edit'])->shallow();

    // Travel Resources
    Route::resource('travels.addresses', 'TravelAddressController')->except(['create', 'edit'])->shallow();
    Route::resource('travels.bids', 'TravelBidController')->except(['create', 'edit'])->shallow();
    Route::resource('travels.categories', 'TravelCategoryController')->except(['create', 'edit'])->shallow();
    Route::resource('travels.comments', 'TravelCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('travels.images', 'TravelImageController')->except(['create', 'edit'])->shallow();
    Route::resource('travels.watchables', 'TravelWatchableController')->except(['create', 'edit'])->shallow();

    // User Resources
    Route::resource('users.addresses', 'UserAddressController')->except(['create', 'edit'])->shallow();
    Route::resource('users.ads', 'UserAdController')->except(['edit'])->shallow();
    Route::resource('users.bids', 'UserBidController')->except(['create', 'edit'])->shallow();
    Route::resource('users.comments', 'UserCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('users.communities', 'UserCommunityController')->except(['edit'])->shallow();
    Route::resource('users.feedbacks', 'UserFeedbackController')->except(['create', 'edit'])->shallow();
    Route::resource('users.images', 'UserImageController')->except(['create', 'edit'])->shallow();
    Route::resource('users.jobs', 'UserJobController')->except(['edit'])->shallow();
    Route::resource('users.products', 'UserProductController')->except(['edit'])->shallow();
    Route::resource('users.real-estates', 'UserRealEstateController')->except(['edit'])->shallow();
    Route::resource('users.services', 'UserServiceController')->except(['edit'])->shallow();
    Route::resource('users.travels', 'UserTravelController')->except(['edit'])->shallow();
    Route::resource('users.vehicles', 'UserVehicleController')->except(['edit'])->shallow();
    Route::resource('users.watchables', 'UserWatchableController')->except(['create', 'edit'])->shallow();

    // Vehicle Resources
    Route::resource('vehicles.addresses', 'VehicleAddressController')->except(['create', 'edit'])->shallow();
    Route::resource('vehicles.bids', 'VehicleBidController')->except(['create', 'edit'])->shallow();
    Route::resource('vehicles.categories', 'VehicleCategoryController')->except(['create', 'edit'])->shallow();
    Route::resource('vehicles.comments', 'VehicleCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('vehicles.images', 'VehicleImageController')->except(['create', 'edit'])->shallow();
    Route::resource('vehicles.watchables', 'VehicleWatchableController')->except(['create', 'edit'])->shallow();

    // Wholesale Actions
    Route::get('wholesales/requests', 'WholesaleRequestController@index')->name('wholesales.requests.index');
    Route::post('wholesales/requests', 'WholesaleRequestController@request')->name('wholesales.requests.store');
    Route::put('wholesales/requests/{wholesaleRequest}/approve', 'WholesaleRequestController@approve')->name('wholesales.requests.approve');
    Route::put('wholesales/requests/{wholesaleRequest}/deny', 'WholesaleRequestController@deny')->name('wholesales.requests.deny');

    // Accounts
    Route::get('/account', 'AccountController')->name('account');
    Route::get('/listings', 'ListingController')->name('listings');
    Route::get('/analytics', 'AnalyticsController')->name('analytics');

    
    // Stripe
    Route::post('/stripe/checkout', 'StripeController@checkout')->name('stripe.checkout');
    Route::get('/stripe/success', 'StripeController@success')->name('stripe.success');
    Route::get('/stripe/cancel', 'StripeController@cancel')->name('stripe.cancel');
    Route::get('/stripe/connect/success', 'StripeController@connectSuccess')->name('stripe.connect.success');

    // Cart
    Route::get('/cart', 'CartController@show')->name('cart.show');
    Route::post('/cart', 'CartController@add')->name('cart.add');
    Route::put('/cart/{id}', 'CartController@update')->name('cart.update');
    Route::delete('/cart/{id}', 'CartController@remove')->name('cart.remove');
    Route::delete('/cart/clear', 'CartController@clear')->name('cart.clear');

app/Address.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Address extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    public function addressable()
    {
        return $this->morphTo();
    }

    public function getPartialAttribute()
    {
        $partialAddress = "";

        if (isset($this->suburb) && isset($this->state)) {
            $partialAddress = "{$this->suburb}, {$this->state}";
        } else if (isset($this->city) && isset($this->country)) {
            $partialAddress = "{$this->city}, {$this->country}";
        }
        
        return $partialAddress;
    }
}

app/Travel.php
<?php

namespace App;

use App\Scopes\StatusScope;
use App\Scopes\UserStatusScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Nicolaslopezj\Searchable\SearchableTrait;

class Travel extends Model
{
    use SearchableTrait, SoftDeletes;

    protected $table = 'travels';

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new StatusScope);
        static::addGlobalScope(new UserStatusScope);
    }

    protected $guarded = [
        'price',
        'status',
    ];

    protected $dates = [
        'date_from',
        'date_to',
    ];

    protected $searchable = [
        'columns' => [
            'travels.name' => 10,
        ],
    ];

    public function address()
    {
        return $this->morphOne('App\Address', 'addressable');
    }

    public function bids()
    {
        return $this->morphMany('App\Bid', 'biddable');
    }

    public function categories()
    {
        return $this->morphToMany('App\Category', 'categorizable');
    }

    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }

    public function images()
    {
        return $this->morphMany('App\Image', 'imageable');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function users()
    {
        return $this->morphToMany('App\User', 'watchable');
    }

    public function scopeNotFromUser($query)
    {
        return $query->whereHas('user', function ($subQuery) {
            $subQuery->whereNotIn('id', [Auth::id()]);
        });
    }

    public function getFormattedPriceAttribute()
    {
        return number_format($this->price, 2, '.', ',');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Nicolaslopezj\Searchable\SearchableTrait;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable, SoftDeletes, SearchableTrait;

    protected $guarded = [
        'type',
        'status',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $dates = ['birth_date'];

    protected $searchable = [
        'columns' => [
            'users.first_name' => 10,
            'users.last_name' => 10,
        ],
    ];

    public function address()
    {
        return $this->morphOne('App\Address', 'addressable');
    }

    public function ads()
    {
        return $this->hasMany('App\Ad');
    }

    public function bids()
    {
        return $this->hasMany('App\Bid');
    }

    public function comments()
    {
        return $this->hasMany('App\Comment');
    }

    public function communities()
    {
        return $this->hasMany('App\Community');
    }

    public function feedbacks()
    {
        return $this->hasMany('App\Feedback');
    }

    public function image()
    {
        return $this->morphOne('App\Image', 'imageable')->latest();
    }

    public function jobs()
    {
        return $this->hasMany('App\Job');
    }

    public function jobWatchlist()
    {
        return $this->morphedByMany('App\Job', 'watchable')
                    ->withPivot('id');
    }

    public function memberships()
    {
        return $this->belongsToMany('App\Membership')
            ->as('membership')
            ->withPivot(
                'sales_count',
                'sales_cost'
            )
            ->withTimestamps();
    }

    public function products()
    {
        return $this->hasMany('App\Product');
    }

    public function productWatchlist()
    {
        return $this->morphedByMany('App\Product', 'watchable')
                    ->withPivot('id');
    }

    public function realEstates()
    {
        return $this->hasMany('App\RealEstate');
    }

    public function realEstateWatchlist()
    {
        return $this->morphedByMany('App\RealEstate', 'watchable')
                    ->withPivot('id');
    }

    public function services()
    {
        return $this->hasMany('App\Service');
    }

    public function serviceWatchlist()
    {
        return $this->morphedByMany('App\Service', 'watchable')
                    ->withPivot('id');
    }

    public function travels()
    {
        return $this->hasMany('App\Travel');
    }

    public function travelWatchlist()
    {
        return $this->morphedByMany('App\Travel', 'watchable')
                    ->withPivot('id');
    }

    public function vehicles()
    {
        return $this->hasMany('App\Vehicle');
    }

    public function vehicleWatchlist()
    {
        return $this->morphedByMany('App\Vehicle', 'watchable')
                    ->withPivot('id');
    }

    public function requests()
    {
        return $this->hasMany('App\WholesaleRequest', 'vendor_id');
    }

    public function wholesaleRequests()
    {
        return $this->hasMany('App\WholesaleRequest', 'buyer_id');
    }

    public function getFullNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }

    public function getProfilePlaceholderAttribute()
    {
        return $this->gender === 'Male' ? asset('img/matt.jpg') : asset('img/kristy.jpg');
    }

    public function getIsActiveAttribute()
    {
        return $this->status === 'active' ? true : false;
    }

    public function getIsBusinessManAttribute()
    {
        return $this->type === 'Business' ? true : false;
    }

    public function scopeActive($query)
    {
        return $query->whereStatus('active');
    }
}

resources/views/app/job-info.blade.php
@extends('layouts.app')

@section('title')
    {{ $job->name }}
@endsection

@push('styles')
    <link
    href="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css"
    rel="stylesheet"
    />
@endpush

@section('content')
    @if($errors->any())
        <div class="my-5 mx-3 md:mx-5 lg:mx-20">
            <div class="ui error message w-full lg:w-1/2">
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </div>
        </div>
    @endif
    <div class="my-5 mt-10 mx-3 md:mx-5 lg:mx-20 md:flex justify-center">
        @if ($job->image)
            <div class="w-full md:w-1/2 mr-5">
                <div
                    class="fotorama"
                    data-nav="thumbs"
                    data-allowfullscreen="true"
                    data-loop="true"
                    data-autoplay="true"
                    data-width="100%"
                >
                    <a href="{{ asset($job->image->src) }}">
                        <img src="{{ asset($job->image->src) }}" />
                    </a>
                </div>
            </div>              
        @else
            <div class="w-full md:w-1/2 mr-5">
                <div class="ui rounded-lg">
                    <img src="{{ asset('img/placeholder.jpg') }}" />
                </div>
            </div>             
        @endif
        <div class="w-full md:w-1/2 lg:ml-5 mt-5 md:mt-0">
            <h1 class="font-bold text-gray-900 text-4xl mb-5">
                {{ $job->name }}
            </h1>
            <div class="my-10">
                <div class="font-bold text-blue-700 text-2xl mb-5">Description</div>
                <p class="text-gray-900 text-lg">
                    {!! $job->description !!}
                </p>
            </div>
            <div class="my-10">
                <div class="font-bold text-blue-700 text-2xl mb-5">Details</div>
                <div class="flex">
                    <div class="mr-20 w-1/2">
                        <div class="ui list">
                            <div class="item mb-5">
                                <div class="font-bold text-blue-700">Company Name</div>
                                <p class="text-gray-900 text-lg">
                                    {{ $job->company_name }}
                                </p>
                            </div>
                        </div>
                        <div class="ui list">
                            <div class="item mb-5">
                                <div class="font-bold text-blue-700">Type</div>
                                <p class="text-gray-900 text-lg">
                                    {{ $job->type }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>            
            <div class="my-5">
                <div class="font-bold text-blue-700 text-2xl mb-5">Address</div>
                <div class="flex">
                    <div class="mr-20">
                        <div class="ui list">
                            <div class="item mb-5">
                                <div class="font-bold text-blue-700">Country</div>
                                <p class="text-gray-900 text-lg">
                                    {{ $job->address->country ?? 'Not Indicated' }}
                                </p>
                            </div>
                        </div>
                        <div class="ui list">
                            <div class="item mb-5">
                                <div class="font-bold text-blue-700">State</div>
                                <p class="text-gray-900 text-lg">
                                    {{ $job->address->state ?? 'Not Indicated' }}
                                </p>
                            </div>
                        </div>
                        <div class="ui list">
                            <div class="item mb-5">
                                <div class="font-bold text-blue-700">Suburb</div>
                                <p class="text-gray-900 text-lg">
                                    {{ $job->address->suburb ?? 'Not Indicated' }}
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="ml-20">
                        <div class="ui list">
                            <div class="item mb-5">
                                <div class="font-bold text-blue-700">City</div>
                                <p class="text-gray-900 text-lg">
                                    {{ $job->address->city ?? 'Not Indicated' }}
                                </p>
                            </div>
                        </div>
                        <div class="ui list">
                            <div class="item mb-5">
                                <div class="font-bold text-blue-700">Post Code</div>
                                <p class="text-gray-900 text-lg">
                                    {{ $job->address->post_code ?? 'Not Indicated' }}
                                </p>
                            </div>
                        </div>
                        <div class="ui list">
                            <div class="item mb-5">
                                <div class="font-bold text-blue-700">Street Name</div>
                                <p class="text-gray-900 text-lg">
                                    {{ $job->address->street_name ?? 'Not Indicated' }}
                                </p>
                            </div>
                        </div>
                        <div class="ui list">
                            <div class="item mb-5">
                                <div class="font-bold text-blue-700">Number</div>
                                <p class="text-gray-900 text-lg">
                                    {{ $job->address->number ?? 'Not Indicated' }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="rounded-lg flex bg-gray-100 shadow hover:shadow-lg w-full lg:w-2/3 p-5">
                <div class="flex items-center">
                    <img
                        class="w-20 h-20 rounded-full mr-5"
                        src="{{ asset($job->user->image->src ?? $job->user->profile_placeholder) }}"
                    />
                    <div>
                        <p class="text-blue-700 leading-none">
                            {{ $job->user->full_name }}
                        </p>
                        <p class="text-gray-900">
                            @isset($job->user->address)
                                {{ Str::limit($job->user->address->partial, 25) }}
                            @endisset
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="my-10 mb-20 mx-3 lg:mx-20 flex items-center justify-center">
        <div class="ui threaded comments w-full md:w-1/2">
            <h3 class="ui dividing header blue">
                Questions and Answers ({{ $job->comments->count() }})
            </h3>
            @foreach ($job->comments as $comment)
                <div class="comment">
                    <span class="avatar">
                        <img
                            src="{{ asset($comment->user->image->src ?? $comment->user->profile_placeholder) }}"
                        />
                    </span>
                    <div class="content">
                        <span class="author">{{ $comment->user->full_name }}</span>
                        <div class="metadata">
                            <span class="date"
                                >{{ $comment->created_at ? $comment->created_at->diffForHumans() : 'Not Indicated' }}</span
                            >
                            @if ($comment->reply)
                                <span class="ui mini green label">Answered</span>
                            @endif
                        </div>
                        <div class="text">
                            <p class="text-lg">
                                {{ $comment->comment }}
                            </p>
                        </div>
                        @if (!$comment->reply)
                            @can('update-comment', $comment)
                                <div class="actions reply-comment">
                                    <a class="reply">Reply</a>
                                </div>
                                <form
                                    action="{{ route('comments.update', $comment->id) }}"
                                    method="POST"
                                    class="ui reply form hidden"
                                >
                                    @csrf
                                    @method('PUT')
                                    <input
                                        type="hidden"
                                        name="user_id"
                                        value="{{ Auth::id() }}"
                                    />
                                    <input
                                        type="hidden"
                                        name="comment"
                                        value="{{ $comment->comment }}"
                                    />
                                    <input
                                        type="hidden"
                                        name="replied_at"
                                        value="{{ now() }}"
                                    />
                                    <div class="field">
                                        <textarea name="reply"></textarea>
                                    </div>
                                    <button
                                        type="submit"
                                        class="ui primary submit labeled icon button"
                                    >
                                        <i class="icon edit"></i> Add Reply
                                    </button>
                                </form>
                            @endcan
                        @endif
                    </div>
                    @if ($comment->reply)
                        <div class="comments">
                            <div class="comment">
                                <span class="avatar">
                                    <img
                                        src="{{ asset($comment->commentable->user->image->src ?? $comment->commentable->user->profile_placeholder) }}"
                                    />
                                </span>
                                <div class="content">
                                    <span class="author"
                                        >{{ $comment->commentable->user->full_name }}</span
                                    >
                                    <div class="metadata">
                                        <span class="date"
                                            >{{ $comment->replied_at->diffForHumans()
                                            }}</span
                                        >
                                    </div>
                                    <div class="text">
                                        <p class="text-lg">
                                          {{ $comment->reply }}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endif
                </div>
            @endforeach
            @auth
                @if (Gate::check('create-comment'))
                    <form
                        action="{{ route('jobs.comments.store', $job->id) }}"
                        method="post"
                        class="ui reply form"
                    >
                        @csrf
                        <input type="hidden" name="user_id" value="{{ Auth::id() }}" />
                        <div class="field">
                            <textarea name="comment"></textarea>
                        </div>
                        <button type="submit" class="ui primary submit labeled icon button">
                            <i class="icon edit"></i> Add Comment
                        </button>
                    </form>
                @else
                    <div class="ui message">
                        <p> Please activate your account in order to post a comment. </p>
                    </div>
                @endif
            @endauth
        </div>
    </div>
@endsection

@push('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.js"></script>
    <script>
        $(".reply-comment").on("click", function() {
            $(this)
                .next()
                .toggleClass("hidden");
        });
    </script>
@endpush