routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Configurations
Route::redirect('/', '/home');
Auth::routes(['verify' => true]);

// Free Views
Route::view('/about', 'app.about')->name('about');
Route::view('/contact-us', 'app.contact-us')->name('contact-us');
Route::view('/faqs', 'app.faqs')->name('faqs');
Route::view('/posting-policy', 'app.posting-policy')->name('posting-policy');
Route::view('/privacy-policy', 'app.privacy-policy')->name('privacy-policy');
Route::view('/terms-of-use', 'app.terms-of-use')->name('terms-of-use');

// Free Routes
Route::get('/home', 'HomeController')->name('home');
Route::get('/retails', 'RetailController')->name('retails');
Route::get('/wholesales', 'WholesaleController')->name('wholesales');
Route::get('/auctions', 'AuctionController')->name('auctions');
Route::get('/reverse-auctions', 'ReverseAuctionController')->name('reverse-auctions');
Route::get('/search', 'SearchController@search')->name('search');
Route::get('/suggestion', 'SearchController@suggestion')->name('suggestion');
Route::get('/jobs/search', 'SearchController@searchJob')->name('search.job');
Route::get('/real-estates/search', 'SearchController@searchRealEstate')->name('search.real-estate');
Route::get('/travels/search', 'SearchController@searchTravel')->name('search.travel');
Route::get('/vehicles/search', 'SearchController@searchVehicle')->name('search.vehicle');

// Throttle
Route::group(['middleware' => ['throttle:60,1']], function () {
    // User Auth
    Route::namespace('Auth')->group(function () {
        Route::get('/logout', 'LoginController@logout')->name('logout');

        Route::get('/login/facebook', 'LoginController@facebookLogin')->name('facebook.login');
        Route::get('/login/facebook/callback', 'LoginController@facebookCallback')->name('facebook.callback');

        Route::get('/login/google', 'LoginController@googleLogin')->name('google.login');
        Route::get('/login/google/callback', 'LoginController@googleCallback')->name('google.callback');

        Route::get('/login/linkedin', 'LoginController@linkedinLogin')->name('linkedin.login');
        Route::get('/login/linkedin/callback', 'LoginController@linkedinCallback')->name('linkedin.callback');

        Route::get('/login/instagram', 'LoginController@instagramLogin')->name('instagram.login');
        Route::get('/login/instagram/callback', 'LoginController@instagramCallback')->name('instagram.callback');
    });

    // Community Resources
    Route::resource('communities.categories', 'CommunityCategoryController')->except(['create', 'edit'])->shallow();
    Route::resource('communities.comments', 'CommunityCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('communities.images', 'CommunityImageController')->except(['create', 'edit'])->shallow();

    // Job Resources
    Route::resource('jobs.addresses', 'JobAddressController')->except(['create', 'edit'])->shallow();
    Route::resource('jobs.categories', 'JobCategoryController')->except(['create', 'edit'])->shallow();
    Route::resource('jobs.comments', 'JobCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('jobs.images', 'JobImageController')->except(['create', 'edit'])->shallow();

    // Product Resources
    Route::resource('products.addresses', 'ProductAddressController')->except(['create', 'edit'])->shallow();
    Route::resource('products.bids', 'ProductBidController')->except(['create', 'edit'])->shallow();
    Route::resource('products.categories', 'ProductCategoryController')->except(['create', 'edit'])->shallow();
    Route::resource('products.comments', 'ProductCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('products.images', 'ProductImageController')->except(['create', 'edit'])->shallow();
    Route::resource('products.watchables', 'ProductWatchableController')->except(['create', 'edit'])->shallow();

    // Real Estate Resources
    Route::resource('real-estates.addresses', 'RealEstateAddressController')->except(['create', 'edit'])->shallow();
    Route::resource('real-estates.bids', 'RealEstateBidController')->except(['create', 'edit'])->shallow();
    Route::resource('real-estates.categories', 'RealEstateCategoryController')->except(['create', 'edit'])->shallow();
    Route::resource('real-estates.comments', 'RealEstateCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('real-estates.images', 'RealEstateImageController')->except(['create', 'edit'])->shallow();
    Route::resource('real-estates.watchables', 'RealEstateWatchableController')->except(['create', 'edit'])->shallow();

    // Service Resources
    Route::resource('services.addresses', 'ServiceAddressController')->except(['create', 'edit'])->shallow();
    Route::resource('services.bids', 'ServiceBidController')->except(['create', 'edit'])->shallow();
    Route::resource('services.categories', 'ServiceCategoryController')->except(['create', 'edit'])->shallow();
    Route::resource('services.comments', 'ServiceCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('services.feedbacks', 'ServiceFeedbackController')->except(['create', 'edit'])->shallow();
    Route::resource('services.images', 'ServiceImageController')->except(['create', 'edit'])->shallow();
    Route::resource('services.watchables', 'ServiceWatchableController')->except(['create', 'edit'])->shallow();

    // Travel Resources
    Route::resource('travels.addresses', 'TravelAddressController')->except(['create', 'edit'])->shallow();
    Route::resource('travels.bids', 'TravelBidController')->except(['create', 'edit'])->shallow();
    Route::resource('travels.categories', 'TravelCategoryController')->except(['create', 'edit'])->shallow();
    Route::resource('travels.comments', 'TravelCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('travels.images', 'TravelImageController')->except(['create', 'edit'])->shallow();
    Route::resource('travels.watchables', 'TravelWatchableController')->except(['create', 'edit'])->shallow();

    // User Resources
    Route::resource('users.addresses', 'UserAddressController')->except(['create', 'edit'])->shallow();
    Route::resource('users.ads', 'UserAdController')->except(['edit'])->shallow();
    Route::resource('users.bids', 'UserBidController')->except(['create', 'edit'])->shallow();
    Route::resource('users.comments', 'UserCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('users.communities', 'UserCommunityController')->except(['edit'])->shallow();
    Route::resource('users.feedbacks', 'UserFeedbackController')->except(['create', 'edit'])->shallow();
    Route::resource('users.images', 'UserImageController')->except(['create', 'edit'])->shallow();
    Route::resource('users.jobs', 'UserJobController')->except(['edit'])->shallow();
    Route::resource('users.products', 'UserProductController')->except(['edit'])->shallow();
    Route::resource('users.real-estates', 'UserRealEstateController')->except(['edit'])->shallow();
    Route::resource('users.services', 'UserServiceController')->except(['edit'])->shallow();
    Route::resource('users.travels', 'UserTravelController')->except(['edit'])->shallow();
    Route::resource('users.vehicles', 'UserVehicleController')->except(['edit'])->shallow();
    Route::resource('users.watchables', 'UserWatchableController')->except(['create', 'edit'])->shallow();

    // Vehicle Resources
    Route::resource('vehicles.addresses', 'VehicleAddressController')->except(['create', 'edit'])->shallow();
    Route::resource('vehicles.bids', 'VehicleBidController')->except(['create', 'edit'])->shallow();
    Route::resource('vehicles.categories', 'VehicleCategoryController')->except(['create', 'edit'])->shallow();
    Route::resource('vehicles.comments', 'VehicleCommentController')->except(['create', 'edit'])->shallow();
    Route::resource('vehicles.images', 'VehicleImageController')->except(['create', 'edit'])->shallow();
    Route::resource('vehicles.watchables', 'VehicleWatchableController')->except(['create', 'edit'])->shallow();

    // Wholesale Actions
    Route::get('wholesales/requests', 'WholesaleRequestController@index')->name('wholesales.requests.index');
    Route::post('wholesales/requests', 'WholesaleRequestController@request')->name('wholesales.requests.store');
    Route::put('wholesales/requests/{wholesaleRequest}/approve', 'WholesaleRequestController@approve')->name('wholesales.requests.approve');
    Route::put('wholesales/requests/{wholesaleRequest}/deny', 'WholesaleRequestController@deny')->name('wholesales.requests.deny');

    // Accounts
    Route::get('/account', 'AccountController')->name('account');
    Route::get('/listings', 'ListingController')->name('listings');
    Route::get('/analytics', 'AnalyticsController')->name('analytics');

    
    // Stripe
    Route::post('/stripe/checkout', 'StripeController@checkout')->name('stripe.checkout');
    Route::get('/stripe/success', 'StripeController@success')->name('stripe.success');
    Route::get('/stripe/cancel', 'StripeController@cancel')->name('stripe.cancel');
    Route::get('/stripe/connect/success', 'StripeController@connectSuccess')->name('stripe.connect.success');

    // Cart
    Route::get('/cart', 'CartController@show')->name('cart.show');
    Route::post('/cart', 'CartController@add')->name('cart.add');
    Route::put('/cart/{id}', 'CartController@update')->name('cart.update');
    Route::delete('/cart/{id}', 'CartController@remove')->name('cart.remove');
    Route::delete('/cart/clear', 'CartController@clear')->name('cart.clear');

resources/views/admin/communities.blade.php
@extends('layouts.admin')

@section('title')
    Communities
@endsection

@section('content')
    <div class="row">
        <div class="col">
            @unless ($communities->count())
                <div class="alert alert-default" role="alert">
                    There are no communities registered as of now.
                </div>
            @endunless
            @if ($communities->count())
                <div class="card shadow">
                    <div class="card-header border-0">
                        <h3 class="mb-0">Communities</h3>
                    </div>
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">Name</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($communities as $community)
                                    <tr>
                                        <td>{{ $community->name }}</td>
                                        <td class="font-bold">
                                            {{ ucwords($community->status) }}
                                        </td>
                                        <td>
                                            <button
                                                class="btn btn-primary btn-sm view-community"
                                                type="button"
                                                data-toggle="modal"
                                                data-target="#communityInfo"
                                                data-id="{{ $community->id }}"
                                            >
                                                View
                                            </button>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer py-4">
                        {{ $communities->links('vendor.pagination.argon-dashboard') }}
                    </div>                    
                </div>
            @endif
        </div>
    </div>
    <div
        class="modal fade"
        id="communityInfo"
        tabindex="-1"
        role="dialog"
        aria-labelledby="communityInfoLabel"
        aria-hidden="true"
    >
        <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="communityInfoLabel"></h5>
                    <button
                        type="button"
                        class="close"
                        data-dismiss="modal"
                        aria-label="Close"
                    >
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <dl class="row">
                        <dt class="col-sm-5 my-2">Name</dt>
                        <dd class="col-sm-7 my-2" id="communityName"></dd>
                        <dt class="col-sm-5 my-2">User</dt>
                        <dd class="col-sm-7 my-2" id="communityUser"></dd>
                        <dt class="col-sm-5 my-2">Email</dt>
                        <dd class="col-sm-7 my-2" id="communityEmail"></dd>
                        <dt class="col-sm-5 my-2">Company Number</dt>
                        <dd class="col-sm-7 my-2" id="communityCompanyNumber"></dd>
                        <dt class="col-sm-5 my-2">Registration</dt>
                        <dd class="col-sm-7 my-2" id="communityRegistration"></dd>
                        <dt class="col-sm-5 my-2">PO Box Address</dt>
                        <dd class="col-sm-7 my-2" id="communityPOBoxAddress"></dd>
                        <dt class="col-sm-5 my-2">Description</dt>
                        <dd class="col-sm-7 my-2" id="communityDescription"></dd>
                        <dt class="col-sm-5 my-2">Date Time</dt>
                        <dd class="col-sm-7 my-2" id="communityDateTime"></dd>
                        <dt class="col-sm-5 my-2">Start Time</dt>
                        <dd class="col-sm-7 my-2" id="communityStartTime"></dd>
                        <dt class="col-sm-5 my-2">Finish Time</dt>
                        <dd class="col-sm-7 my-2" id="communityFinishTime"></dd>
                        <dt class="col-sm-5 my-2">Parking/Disablity Dropbox</dt>
                        <dd class="col-sm-7 my-2" id="communityDropbox"></dd>
                        <dt class="col-sm-5 my-2">Pick Up Type</dt>
                        <dd class="col-sm-7 my-2" id="communityPickUpType"></dd>
                        <dt class="col-sm-5 my-2">Status</dt>
                        <dd class="col-sm-7 my-2" id="communityStatus"></dd>
                    </dl>
                </div>
                <div class="modal-footer">
                    <button
                        type="button"
                        class="btn btn-secondary"
                        data-dismiss="modal"
                    >
                        Close
                    </button>
                    <button
                        id="communityAction"
                        type="button"
                        class="btn btn-primary"
                    ></button>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $(".view-community").on("click", function() {
            let url = '{{ route("admin.communities.show", ":id") }}'.replace(':id', $(this).data('id'));

            $.ajax({
                url: url,
                success: function (response) {
                    var community = response.community
                    $("#communityInfoLabel").text(community.name);
                    $("#communityUser").text(`${community.user.first_name} ${community.user.last_name}`);
                    $("#communityName").text(community.name);

                    $("#communityEmail").text(community.email);
                    $("#communityCompanyNumber").text(community.company_number || 'None');
                    $("#communityRegistration").text(community.registration || 'None');
                    $("#communityPOBoxAddress").text(community.po_box_address);
                    $("#communityDescription").text(community.description);

                    let date = new Date(community.date_time).toLocaleDateString();
                    let start = new Date(community.start_time).toLocaleTimeString();
                    let finish = new Date(community.finish_time).toLocaleTimeString();
                    $("#communityDateTime").text(community.date_time ? date : 'None');
                    $("#communityStartTime").text(community.start_time ? start : 'None');
                    $("#communityFinishTime").text(community.finish_time ? finish : 'None');

                    $("#communityDropbox").text(community.parking_or_disability_drop_box ? 'Yes' : 'No');
                    $("#communityPickUpType").text(community.pick_up_type);

                    let status = community.status
                    $("#communityStatus").text(status.charAt(0).toUpperCase() + status.slice(1));

                    $("#communityAction").text(
                        community.status === 'active' ? 'Set as "Inactive"' :  'Set as Active'
                    );

                    $("#communityAction").on("click", function() {
                        $(`#communityToggleForm input[name='status']`).val(
                            community.status === "active" ? "inactive" : "active"
                        );
                        $("#communityToggleForm").attr(
                            "action",
                            `/admin/communities/${community.id}/toggle`
                        );
                        $("#communityToggleForm").submit();
                    });

                }
            })


        });
    </script>
@endpush

resources/views/admin/email-reminders.blade.php
@extends('layouts.admin')

@section('title')
    Email Reminder
@endsection

@section('content')
    <div class="row">
        <div class="col">
            <div class="card shadow">
                <div class="card-header border-0">
                    <h3 class="mb-0">Email Reminder</h3>
                </div>
                <div class="card body p-4">
                    <form
                        method="POST"
                        action="{{ route('admin.email-reminders.send') }}"
                    >
                        @csrf
                        <div class="form-group">
                            <label for="subject">Subject</label>
                            <input
                                id="subject"
                                name="subject"
                                type="text"
                                class="form-control"
                                placeholder="Subject"
                                value="{{ old('subject') }}"
                                required
                                autofocus
                            />
                        </div>
                        <div class="form-group">
                            <label for="body">Message</label>
                            <textarea
                                id="body"
                                name="body"
                                class="form-control"
                                rows="5"
                                required
                            >{{ old('body') }}</textarea>
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">
                            Send Reminder
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection